# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# # https://aka.ms/yaml
# name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
- main

parameters: 
  - name: terraformVersion
    displayName: Terraform version
    type: string
    values:
      - 1.2.8
      - 1.2.9
      - 1.3.0
      - 1.8.0
    default: 1.8.0

pool:
  vmImage: windows-latest

steps:
- task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
  inputs:
    terraformVersion: ${{ parameters.TerraformVersion }}

- pwsh: terraform init -backend=false
  displayName: Terraform Init
- pwsh: terraform fmt -check
  displayName: Terraform Format Check
- pwsh: terraform validate
  displayName: Terraform Validate
    


